/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-secondary-container": "#745c00",
              "primary": "#000000",
              "on-background": "#1c1b1b",
              "tertiary-container": "#211a1b",
              "on-surface": "#1c1b1b",
              "error": "#ba1a1a",
              "outline": "#747878",
              "cream-bg": "#FCF9F9",
              "inverse-surface": "#313030",
              "primary-container": "#1c1b1b",
              "charcoal": "#1A1A1A",
              "on-tertiary-fixed-variant": "#4e4446",
              "on-primary-fixed-variant": "#474746",
              "champagne-gold": "#D4AF37",
              "surface-container-high": "#ebe7e6",
              "primary-fixed": "#e5e2e1",
              "secondary-fixed": "#ffe088",
              "inverse-primary": "#c8c6c5",
              "on-primary-container": "#858383",
              "tertiary": "#000000",
              "inverse-on-surface": "#f4f0ef",
              "surface-container-lowest": "#ffffff",
              "on-error-container": "#93000a",
              "on-secondary": "#ffffff",
              "surface-dim": "#ddd9d8",
              "error-container": "#ffdad6",
              "background": "#fdf8f8",
              "on-secondary-fixed-variant": "#574500",
              "tertiary-fixed": "#eedfe1",
              "soft-blush": "#F5E6E8",
              "on-tertiary-container": "#8d8183",
              "surface-container": "#f1edec",
              "tertiary-fixed-dim": "#d1c3c5",
              "on-primary-fixed": "#1c1b1b",
              "on-error": "#ffffff",
              "on-primary": "#ffffff",
              "outline-variant": "#c4c7c7",
              "on-tertiary": "#ffffff",
              "secondary": "#735c00",
              "primary-fixed-dim": "#c8c6c5",
              "surface-bright": "#fdf8f8",
              "surface-container-highest": "#e5e2e1",
              "surface-tint": "#5f5e5e",
              "on-surface-variant": "#444748",
              "gold-leaf": "#B8932D",
              "surface-variant": "#e5e2e1",
              "secondary-fixed-dim": "#e9c349",
              "surface-container-low": "#f7f3f2",
              "secondary-container": "#fed65b",
              "on-secondary-fixed": "#241a00",
              "on-tertiary-fixed": "#211a1b",
              "surface": "#fdf8f8"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "section-padding": "120px",
              "gutter": "24px",
              "stack-lg": "48px",
              "section-padding-mobile": "64px",
              "stack-md": "24px",
              "stack-sm": "12px",
              "container-max": "1200px"
      },
      "fontFamily": {
              "display-lg": ["Playfair Display", "serif"],
              "headline-sm": ["Playfair Display", "serif"],
              "body-lg": ["Montserrat", "sans-serif"],
              "headline-md": ["Playfair Display", "serif"],
              "display-lg-mobile": ["Playfair Display", "serif"],
              "body-md": ["Montserrat", "sans-serif"],
              "label-caps": ["Montserrat", "sans-serif"]
      },
      "fontSize": {
              "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
              "headline-sm": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
              "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
              "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
              "display-lg-mobile": ["40px", { "lineHeight": "1.2", "fontWeight": "700" }],
              "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
              "label-caps": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.15em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
